### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by SamvitJ** [xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master#10]
This GitHub repository has no license. Could you please upload a license indicating what permissions users have with regard to this code?

**Comment by SamvitJ** [comment]
In case you want some info on common license types: https://choosealicense.com/.
The MIT license is generally very commonly used for open source deep learning projects.

**Comment by SamvitJ** [comment]
Hi Xia, just wanted to follow up on this!

**Comment by xiahaifeng1995** [comment]
Sorry, I didn’t reply to your message in time, Now I have uploaded the license。

**Comment by SamvitJ** [comment]
Thank you!!
