### ISSUE TITLE
What is criteria of "t_d" and "d" in main code? and efficientnet-b5

### ISSUE THREAD

**Issue by GaengSu** [xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master#22]
Hello :)

I'm so insterested in your work from korea.

While I was reading your code, I had some questions.

1. What is the criteria of "t_d" and "d" in main.py ?
I know that they used in dimensionality reduction, i want to know how to decide that number. (just experiment result?)

2. How to apply another model like efficientnet-b5?
In your paper, you train resnet, wide resnet, and "efficientnet-b5", but in code it isn't existed.
I want to apply efficientnet-b5 and another models like nfnet.
plz tell me how to apply it.
++ If the reason why efficientnet-b5 is not implemented is because pytorch does not officially support it, please let me know the "t_d" and "d" you used. I already know how to use "efficientnet". 

Thanks.

**Comment by Youskrpig** [comment]
> 2\. son why efficientnet-b5 is not implemented is because pytorch does not officially support it, please let m

For efficientnet: pip install efficientnet-pytorch
The dimension of Td seems depends on embeddings_cconcat(such as layer 1 2 3)

**Comment by xiahaifeng1995** [comment]
The dimension of d is just chosen randomly, provided that the random seed is fixed.

**Comment by GaengSu** [comment]
> The dimension of d is just chosen randomly, provided that the random seed is fixed.

thanks for your reply
