### ISSUE TITLE
Can i use another models?

### ISSUE THREAD

**Issue by GaengSu** [xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master#23]
Hello :)

I already have used PaDiM, and I used additionally efficientnet-b5.
I think the performance of that model is better than resnet(and also wide-resnet).
So I want to try the latest model like nfnet, but I don't think it's applied well.
I wonder if I'm using it wrong or PaDim can't use nfnet.

Thanks 😁

**Comment by xiahaifeng1995** [comment]
If the accuracy does not vary very much, I think it is normal, this may be because the extracted features are not very suitable for solving anomaly detection tasks. For example, the features extracted by the transformer are conducive to segmentation,  but not good for classification.

**Comment by GaengSu** [comment]
> If the accuracy does not vary very much, I think it is normal, this may be because the extracted features are not very suitable for solving anomaly detection tasks. For example, the features extracted by the transformer are conducive to segmentation, but not good for classification.

thanks for you reply
