### ISSUE TITLE
About the PRO-score

### ISSUE THREAD

**Issue by Classmate-Huang** [xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master#5]
As the title, Do you know how to calculate the PRO-score for segmentation? 

Sincerely hope that you can take time to reproduce it.

**Comment by xiahaifeng1995** [comment]
Maybe you can refer to this project:
https://github.com/YoungGod/DFR/blob/a942f344570db91bc7feefc6da31825cf15ba3f9/DFR-source/anoseg_dfr.py#L447

**Comment by Classmate-Huang** [comment]
> Maybe you can refer to this project:
> https://github.com/YoungGod/DFR/blob/a942f344570db91bc7feefc6da31825cf15ba3f9/DFR-source/anoseg_dfr.py#L447

thx very much!
