### ISSUE TITLE
Threshold selection for the testing 

### ISSUE THREAD

**Issue by xfby2016** [xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master#7]
Thank you for your open source！

I found that the threshold of the test phase mask comes from the real mask of the test set,is this necessary?. Is there any other way to get the threshold? Or how much should be set by default? 
Thank you!

**Comment by xiahaifeng1995** [comment]
Hi, 
You can get optimal threshold using ground_truth masks or estimate threshold based on positive samples, which may take several attempts to get good results. 
Please refer to this project:
https://github.com/plutoyuxie/AutoEncoder-SSIM-for-unsupervised-anomaly-detection-/blob/1bd6651a77d796445156d2a3e08d11d805079367/test.py#L59

**Comment by xiahaifeng1995** [comment]
Hi, 
You can get optimal threshold using ground_truth masks or estimate threshold based on positive samples, which may take several attempts to get good results. 
Please refer to this project:
https://github.com/plutoyuxie/AutoEncoder-SSIM-for-unsupervised-anomaly-detection-/blob/1bd6651a77d796445156d2a3e08d11d805079367/test.py#L59

**Comment by xfby2016** [comment]
Thank you for your advice，In addition, for different types of training samples can be combined training?
I mean bottle、cabel different categories, can train together to save one model file?
